--- 
action: 
  - 
    service: light.turn_on
    target: light_target
  - 
    wait_for_trigger: 
      entity_id: motion_entity
      from: "on"
      platform: state
      to: "off"
  - 
    delay: no_motion_wait
  - 
    service: light.turn_off
    target: light_target
blueprint: 
  domain: automation
  input: 
    light_target: 
      name: Light
      selector: 
        target: 
          entity: 
            domain: light
    motion_entity: 
      name: "Czujnik ruchu"
      selector: 
        entity: 
          device_class: motion
          domain: binary_sensor
    no_motion_wait: 
      default: 5
      description: "Time to wait until the light should be turned off."
      name: "Wait time"
      selector: 
        number: 
          max: 3600
          min: 0
          unit_of_measurement: seconds
    time_limit_after: 
      default: "15:30:00"
      description: "Automatyzacja będzie działać tylko wtedy, gdy czas będzie późniejszy niż ta wartość"
      name: "Uruchom tylko po czasie."
      selector: 
        entity: 
          domain: input_datetime
    time_limit_before: 
      default: 27000
      description: "Automatyzacja będzie działać tylko wtedy, gdy czas będzie wcześniejszy niż ta wartość"
      name: "Uruchom tylko przed czasem."
      selector: 
        entity: 
          domain: input_datetime
  name: "Czujnik ruchu Warsztat"
  source_url: "https://github.com/home-assistant/core/blob/71af0fac1644821b9303815b680914b9eeca444d/homeassistant/components/automation/blueprints/motion_light.yaml"
condition: 
  - 
    condition: and
    conditions: 
      - 
        after: time_limit_after
        before: time_limit_before
        condition: time
max_exceeded: silent
mode: restart
trigger: 
  entity_id: motion_entity
  from: "off"
  platform: state
  to: "on"
variables: 
  time_limit_after: time_limit_after
  time_limit_before: time_limit_before
